# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: dotman
# Description of the Site
description: Welcome to dotman's personal page
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.pixabay.com/photo/2024/01/29/19/38/mountains-8540699_1280.jpg
# heroimage: ../images/hero-ds.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: whongyi@zju.edu.cn
facebook_username: 100016034496041
twitter_username: dootmaan
instagram_username: dootmaan
linkedin_username: hongyi-wang-8609aa8a
github_username:  Dootmaan
youtube_channel_id: 
reddit_username: dootmaan
behance_username: 
dribbble_username: 
spotify_username: 314bedcquw5bxjqzw4mtetyvtrd4
researchgate_username: Hongyi-Wang-16
steam_username: 76561198207820131

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: dotman

# Name of the Author
author-name: Hongyi WANG
# URL for the Image of the Author
author-image: /assets/images/me3.jpg
# 60 Words About the Author
author-about: Hi there, my name is Hongyi WANG and currently I am a fifth-year Computer Science Ph.D. at Zhejiang University, China. My research interests mainly lie in 3D Medical Image Analysis, Computational Pathology, and Lightweight Models. I am also an enthusiast in electronic devices and software engineering.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Dootmaan

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
